hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("LIBVA_DRIVER_NAME","nvidia")
hl.env("XDG_SESSION_TYPE","wayland")
hl.env("GBM_BACKEND","nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME","nvidia")
hl.env("QT_QPA_PLATFORMTHEME","qt6ct")
hl.env("QT_STYLE_OVERRIDE","kvantum")
hl.env("ADW_DEBUG_COLOR_SCHEME","prefer-dark")
