source = ~/.config/hypr/conf.d/10-monitors.conf
source = ~/.config/hypr/conf.d/20-programs.conf
source = ~/.config/hypr/conf.d/30-autostart.conf
source = ~/.config/hypr/conf.d/40-environment.conf
source = ~/.config/hypr/conf.d/45-permissions.conf
source = ~/.config/hypr/conf.d/50-look-and-feel.conf
source = ~/.config/hypr/conf.d/60-input.conf
source = ~/.config/hypr/conf.d/70-keybindings.conf
source = ~/.config/hypr/conf.d/80-workspaces.conf
source = ~/.config/hypr/conf.d/90-rules.conf
