windowrule {
	name = "sys-monitor size"
	match:title = ^(sys-monitor$)
	float = true
	size = 800 600
}
windowrule {
	name = "calendar size"
	match:title = ^(Calendar$)
	float = true
	size = 800 600
}
