windowrule {
	name = "launch sys-monitor correctly"
	match:title = ^(sys-monitor$)
	float = true
	size = 1000 800
}
windowrule {
	name = "gnome calendar sizing"
	match:title = ^(Calendar$)
	float = true
	size = 1000 800
}
