exec-once = dbus-update-activation-environment --systemd ADW_DEBUG_COLOR_SCHEME QT_QPA_PLATFORMTHEME QT_STYLE_OVERRIDE
exec-once = hyprctl dispatch workspace 1 & quickshell
exec-once = wl-clip-persist --clipboard regular
